/* Generated By:JavaCC: Do not edit this line. SqlParserConstants.java */
package sqlParser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SqlParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMENT_LINE = 6;
  /** RegularExpression Id. */
  int COMMENT_BLOCK = 7;
  /** RegularExpression Id. */
  int O_ASTERISK = 8;
  /** RegularExpression Id. */
  int O_CLOSEPAREN = 9;
  /** RegularExpression Id. */
  int O_OPENPAREN = 10;
  /** RegularExpression Id. */
  int O_COMMA = 11;
  /** RegularExpression Id. */
  int O_PERCENT = 12;
  /** RegularExpression Id. */
  int O_EQUAL = 13;
  /** RegularExpression Id. */
  int O_GREATER = 14;
  /** RegularExpression Id. */
  int O_GREATEREQUAL = 15;
  /** RegularExpression Id. */
  int O_LESS = 16;
  /** RegularExpression Id. */
  int O_LESSEQUAL = 17;
  /** RegularExpression Id. */
  int O_MINUS = 18;
  /** RegularExpression Id. */
  int O_NOTEQUAL2 = 19;
  /** RegularExpression Id. */
  int O_NOTEQUAL = 20;
  /** RegularExpression Id. */
  int INTEGER = 21;
  /** RegularExpression Id. */
  int DIGIT = 22;
  /** RegularExpression Id. */
  int R_AND = 23;
  /** RegularExpression Id. */
  int R_ASC = 24;
  /** RegularExpression Id. */
  int R_BY = 25;
  /** RegularExpression Id. */
  int R_CONNECT = 26;
  /** RegularExpression Id. */
  int R_CREATE = 27;
  /** RegularExpression Id. */
  int R_DESC = 28;
  /** RegularExpression Id. */
  int R_DISTINCT = 29;
  /** RegularExpression Id. */
  int R_DROP = 30;
  /** RegularExpression Id. */
  int R_FROM = 31;
  /** RegularExpression Id. */
  int R_GROUP = 32;
  /** RegularExpression Id. */
  int R_HAVING = 33;
  /** RegularExpression Id. */
  int R_IN = 34;
  /** RegularExpression Id. */
  int R_INSERT = 35;
  /** RegularExpression Id. */
  int R_INTO = 36;
  /** RegularExpression Id. */
  int R_IS = 37;
  /** RegularExpression Id. */
  int R_LIKE = 38;
  /** RegularExpression Id. */
  int R_NOT = 39;
  /** RegularExpression Id. */
  int R_NULL = 40;
  /** RegularExpression Id. */
  int R_OR = 41;
  /** RegularExpression Id. */
  int R_ORDER = 42;
  /** RegularExpression Id. */
  int R_SELECT = 43;
  /** RegularExpression Id. */
  int R_UNIQUE = 44;
  /** RegularExpression Id. */
  int R_UPDATE = 45;
  /** RegularExpression Id. */
  int R_VALUES = 46;
  /** RegularExpression Id. */
  int R_WHERE = 47;
  /** RegularExpression Id. */
  int R_CONSTRAINT = 48;
  /** RegularExpression Id. */
  int R_CTCMD = 49;
  /** RegularExpression Id. */
  int R_PRIMARY = 50;
  /** RegularExpression Id. */
  int R_INTEGER = 51;
  /** RegularExpression Id. */
  int R_VARCHAR = 52;
  /** RegularExpression Id. */
  int R_HORIZONTAL = 53;
  /** RegularExpression Id. */
  int S_IDENTIFIER = 54;
  /** RegularExpression Id. */
  int LETTER = 55;
  /** RegularExpression Id. */
  int SPECIAL_CHARS = 56;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<COMMENT_LINE>",
    "<COMMENT_BLOCK>",
    "\"*\"",
    "\")\"",
    "\"(\"",
    "\",\"",
    "\"%\"",
    "\"=\"",
    "\">\"",
    "\">=\"",
    "\"<\"",
    "\"<=\"",
    "\"-\"",
    "\"<>\"",
    "\"!=\"",
    "<INTEGER>",
    "<DIGIT>",
    "\"AND\"",
    "\"ASC\"",
    "\"BY\"",
    "\"CONNECT\"",
    "\"CREATE\"",
    "\"DESC\"",
    "\"DISTINCT\"",
    "\"DROP\"",
    "\"FROM\"",
    "\"GROUP\"",
    "\"HAVING\"",
    "\"IN\"",
    "\"INSERT\"",
    "\"INTO\"",
    "\"IS\"",
    "\"LIKE\"",
    "\"NOT\"",
    "\"NULL\"",
    "\"OR\"",
    "\"ORDER\"",
    "\"SELECT\"",
    "\"UNIQUE\"",
    "\"UPDATE\"",
    "\"VALUES\"",
    "\"WHERE\"",
    "\"CONSTRAINT\"",
    "\"CREATE TABLE\"",
    "\"PRIMARY KEY\"",
    "\"INTEGER\"",
    "\"VARCHAR\"",
    "\"HORIZONTAL\"",
    "<S_IDENTIFIER>",
    "<LETTER>",
    "\"_\"",
  };

}
