set echo on;

alter session set nls_language = english;
alter session set nls_date_format = 'DD-MON-YYYY';
alter session set nls_date_language = english;


INSERT INTO FLUGHAFEN VALUES ('AKL', 'NZ ', 'Auckland', 'Auckland International');                  
INSERT INTO FLUGHAFEN VALUES ('ALC', 'E  ', 'Alicante', 'Alicante');                                
INSERT INTO FLUGHAFEN VALUES ('ALF', 'N  ', 'Alta', 'Flughafen Alta');                              
INSERT INTO FLUGHAFEN VALUES ('ANC', 'USA', 'Anchorage', 'Ted Stevens AIA');                        
INSERT INTO FLUGHAFEN VALUES ('ARN', 'S  ', 'Stockholm', 'Arlanda');                                
INSERT INTO FLUGHAFEN VALUES ('BCN', 'E  ', 'Barcelona', '');                                       
INSERT INTO FLUGHAFEN VALUES ('BHX', 'GB ', 'Birmingham', '');                                      
INSERT INTO FLUGHAFEN VALUES ('BOS', 'USA', 'Boston', 'Edward Lawrence Logan');                     
INSERT INTO FLUGHAFEN VALUES ('BRE', 'D  ', 'Bremen', 'City Airport Bremen');                       
INSERT INTO FLUGHAFEN VALUES ('BRS', 'GB ', 'Bristol', 'International');                            
INSERT INTO FLUGHAFEN VALUES ('CDG', 'F  ', 'Paris', 'Charles de Gaulle');                          
INSERT INTO FLUGHAFEN VALUES ('CGK', 'ID ', 'Jakarta', 'Sukarno-Hatta Airport');                    
INSERT INTO FLUGHAFEN VALUES ('CGN', 'D  ', 'Koeln', 'Konrad-Adenauer');                            

INSERT INTO FLUGHAFEN VALUES ('CPH', 'DK ', 'Kopenhagen', 'Kastrup');                               
INSERT INTO FLUGHAFEN VALUES ('CPT', 'RSA', 'Kapstadt', '');                                        
INSERT INTO FLUGHAFEN VALUES ('CRT', 'TUN', 'Chartage', 'Tunesien');                                
INSERT INTO FLUGHAFEN VALUES ('DJE', 'TUN', 'Djerba', 'Aeroport de Djerba');                        
INSERT INTO FLUGHAFEN VALUES ('DRS', 'D  ', 'Dresden', 'Dresden Airport');                          
INSERT INTO FLUGHAFEN VALUES ('DUS', 'D  ', 'Duesseldorf', 'Duesseldorf International');            
INSERT INTO FLUGHAFEN VALUES ('EDI', 'GB ', 'Edinburgh', '');                                       
INSERT INTO FLUGHAFEN VALUES ('ERF', 'D  ', 'Erfurt', 'Flughafen Erfurt(ERF)');                     
INSERT INTO FLUGHAFEN VALUES ('FCO', 'I  ', 'Rom', 'Fiumicino');                                    
INSERT INTO FLUGHAFEN VALUES ('FDH', 'D  ', 'Friedrichshafen', 'Bodensee-Airport');                 
INSERT INTO FLUGHAFEN VALUES ('FLR', 'I  ', 'Florenz', 'Peretola');                                 
INSERT INTO FLUGHAFEN VALUES ('FRA', 'D  ', 'Frankfurt', 'Rhein-Main');                             
INSERT INTO FLUGHAFEN VALUES ('GOT', 'S  ', 'Goeteborg', 'Landvetter');                             

INSERT INTO FLUGHAFEN VALUES ('GRZ', 'A  ', 'Graz', 'Flughafen Graz');                              
INSERT INTO FLUGHAFEN VALUES ('GVA', 'CH ', 'Genf', 'Flughafen Genf');                              
INSERT INTO FLUGHAFEN VALUES ('HAJ', 'D  ', 'Hannover', 'Langenhagen');                             
INSERT INTO FLUGHAFEN VALUES ('HHN', 'D  ', 'Hahn', 'Flughafen Hahn');                              
INSERT INTO FLUGHAFEN VALUES ('HKG', 'CHN', 'HongKong', 'HongKong International');                  
INSERT INTO FLUGHAFEN VALUES ('HRG', 'EG ', 'Hurghada', 'International');                           
INSERT INTO FLUGHAFEN VALUES ('IAD', 'USA', 'Washington', 'Dulles');                                
INSERT INTO FLUGHAFEN VALUES ('ISA', 'AUS', 'Mount Isa', 'Queensland');                             
INSERT INTO FLUGHAFEN VALUES ('IST', 'TR ', 'Istanbul', 'Atatürk');                                 
INSERT INTO FLUGHAFEN VALUES ('JFK', 'USA', 'New York', 'John F. Kennedy');                         
INSERT INTO FLUGHAFEN VALUES ('KIX', 'J  ', 'Osaka', 'Kansai');                                     
INSERT INTO FLUGHAFEN VALUES ('KLU', 'D  ', 'Klagenfurt', 'Klagenfurter Flughafen');                
INSERT INTO FLUGHAFEN VALUES ('KSF', 'D  ', 'Kassel', 'Calden');                                    

INSERT INTO FLUGHAFEN VALUES ('LAX', 'USA', 'Los Angeles', '');                                     
INSERT INTO FLUGHAFEN VALUES ('LGW', 'GB ', 'London', 'Gatwick');                                   
INSERT INTO FLUGHAFEN VALUES ('LHR', 'GB ', 'London', 'Heathrow');                                  
INSERT INTO FLUGHAFEN VALUES ('LIM', 'PE ', 'Lima', 'Jorge Chávez');                                
INSERT INTO FLUGHAFEN VALUES ('LPA', 'E  ', 'Las Palmas', 'Las Palmas Airport');                    
INSERT INTO FLUGHAFEN VALUES ('LYS', 'F  ', 'Lyon', 'Saint-Exupéry');                               
INSERT INTO FLUGHAFEN VALUES ('MAN', 'GB ', 'Manchester', '');                                      
INSERT INTO FLUGHAFEN VALUES ('MCO', 'USA', 'Orlando', '');                                         
INSERT INTO FLUGHAFEN VALUES ('MIR', 'TUN', 'Monastir', 'Aéroport Monastir');                       
INSERT INTO FLUGHAFEN VALUES ('MPL', 'F  ', 'Montpellier', 'Montpellier Airport');                  
INSERT INTO FLUGHAFEN VALUES ('MRS', 'F  ', 'Marseille', 'Marseille Provence');                     
INSERT INTO FLUGHAFEN VALUES ('MUC', 'D  ', 'Munich', 'Franz-Josef Strauss');                       
INSERT INTO FLUGHAFEN VALUES ('MVR', 'CMR', 'Maroua', 'Maroua Salek Airport');                      

INSERT INTO FLUGHAFEN VALUES ('NAP', 'I  ', 'Neapel', 'Capodichino');                               
INSERT INTO FLUGHAFEN VALUES ('NCE', 'D  ', 'Nice', '');                                            
INSERT INTO FLUGHAFEN VALUES ('NRT', 'J  ', 'Tokio', 'Narita');                                     
INSERT INTO FLUGHAFEN VALUES ('NUE', 'D  ', 'Nuernberg', '');                                       
INSERT INTO FLUGHAFEN VALUES ('ORD', 'USA', 'Chicago', 'O''Hare');                                   
INSERT INTO FLUGHAFEN VALUES ('ORY', 'F  ', 'Paris', 'Orly');                                       
INSERT INTO FLUGHAFEN VALUES ('OSL', 'N  ', 'Oslo', 'Oslo Gardermoen');                             
INSERT INTO FLUGHAFEN VALUES ('PAD', 'D  ', 'Paderborn', '');                                       
INSERT INTO FLUGHAFEN VALUES ('PEK', 'CHN', 'Peking', 'Beijing Shoudu Guoji Jichang');              
INSERT INTO FLUGHAFEN VALUES ('PMI', 'E  ', 'Palma', 'Aeropuerto de Son Sant Joan');                
INSERT INTO FLUGHAFEN VALUES ('SEA', 'USA', 'Seattle', 'Seattle-Tacoma');                           
INSERT INTO FLUGHAFEN VALUES ('SFO', 'USA', 'San Francisco', '');                                   
INSERT INTO FLUGHAFEN VALUES ('SSH', 'ET ', 'Sharm El Sheikh', 'Sharm El Sheikh Nat. Airport');     

INSERT INTO FLUGHAFEN VALUES ('STN', 'GB ', 'London', 'Stanstead');                                 
INSERT INTO FLUGHAFEN VALUES ('SVO', 'RUS', 'Moskau', 'Scheremetjewo');                             
INSERT INTO FLUGHAFEN VALUES ('SZG', 'A  ', 'Salzburg', 'Salzburg Airport');                        
INSERT INTO FLUGHAFEN VALUES ('TFS', 'E  ', 'Granadilla', 'Teneriffa/Süd');                         
INSERT INTO FLUGHAFEN VALUES ('TLS', 'F  ', 'Toulouse', 'Blagnac');                                 
INSERT INTO FLUGHAFEN VALUES ('TRD', 'N  ', 'Trondheim', 'Vaernes');                                
INSERT INTO FLUGHAFEN VALUES ('TRU', 'PE ', 'Trujillo', '');                                        
INSERT INTO FLUGHAFEN VALUES ('TUN', 'TUN', 'Aeroport de Tunis', 'Tunis');                                     
INSERT INTO FLUGHAFEN VALUES ('TXL', 'D  ', 'Berlin', 'Tegel');                                     
INSERT INTO FLUGHAFEN VALUES ('VCE', 'I  ', 'Venedig', 'Marco Polo');                               
INSERT INTO FLUGHAFEN VALUES ('VIE', 'A  ', 'Wien', 'Schwechat');                                   
INSERT INTO FLUGHAFEN VALUES ('VLC', 'E  ', 'Valencia', 'Manises');                                 
INSERT INTO FLUGHAFEN VALUES ('YDE', 'CMR', 'Yaounde', null);                                         

INSERT INTO FLUGHAFEN VALUES ('YUL', 'CDN', 'Montreal', 'Pierre Elliot Trudeau');                   
INSERT INTO FLUGHAFEN VALUES ('YVR', 'CDN', 'Vancouver', 'Vancouver International');                
INSERT INTO FLUGHAFEN VALUES ('YYC', 'CDN', 'Calgary', 'Municipal Airport');                        
INSERT INTO FLUGHAFEN VALUES ('YYZ', 'CDN', 'Toronto', 'Lester Pearson');                           
INSERT INTO FLUGHAFEN VALUES ('ZAZ', 'E  ', 'Zaragoza', null);                                        
INSERT INTO FLUGHAFEN VALUES ('ZRH', 'CH ', 'Zuerich', 'Kloten');                                   




commit;
  